### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by jcgrenier** [mitre/fusera#151]
Hello! Would it be possible to compile a version of fusera and sracp on a Mac OS? For now, we are only able to get a copy of the compiled programs, which are not compatible with MacOSX.

Thanks for your help.

**Comment by mattrbianchi** [comment]
Hello @jcgrenier!

We originally did provide a Mac binary, but ran into some hiccups with Mac having slightly different C libraries to offer the Go compiler when building. This created a problem in the linux binary which was far more important to the project. The Mac binary was more of a convenience in the early stages of development before the enforcement of Fusra and sracp needing to be in the same location as the data it was attempting to read (that being the cloud where it's quite rare to have a Mac OS). 

Since trying to get the CI pipeline to use a linux image to build the linux binary and a Mac image to build the Mac binary would have been a headache for this lightweight project and Fusera is intended to be used inside a cloud environment anyway, we decided to drop automated builds of the Mac binary in order to continue to serve a linux binary.

That being said, if you still have a use case for having a Mac binary, installing Go is incredibly easy and then you can get a Mac binary. You can get the Go compiler here: https://golang.org/dl/.
Then I have instructions on the Wiki: https://github.com/mitre/fusera/wiki/Installing-Fusera#i-build-my-own-binaries.

As long as the Mac binary is built using a Mac OS and a Linux binary is built with.a Linux distro, the two binaries will work fine. It was trying to cross compile a Linux binary from a Mac OS image in order to keep my pipeline simple that caused the issue in the first paragraph.

**Comment by jcgrenier** [comment]
Hi @mattrbianchi ,

Thanks for your email. I was able to compile using your advice. Thanks a lot!

**Comment by mattrbianchi** [comment]
No problem!
